language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install --upgrade youtube-dl"

# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:/home/travis/build/r0bobo/python_tools_dean
  - /home/travis/build/r0bobo/python_tools_dean/test/test_configreader.py
  - /home/travis/build/r0bobo/python_tools_dean/test/test_youtubesync.py
  - cat /home/travis/.local/share/dean/youtube_dl.json
