language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - export PATH=$PATH:/home/travis/build/r0bobo
  - export PYTHONPATH=$PYTHONPATH:/home/travis/build/r0bobo
  - /home/travis/build/r0bobo/python_tools_dean/test/test_configreader.py

