language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install --upgrade youtube-dl"

# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:/home/travis/build/r0bobo/python_tools_dean
  - ./test/test_all.py
  - echo "Test log:"
  - echo "travis_fold:start:NAME"
  - cat ~/dean_utils_test.log
  - echo "travis_fold:end:NAME"
